### ISSUE TITLE
Replace duplicate code with a global environment variable

### ISSUE THREAD

**Issue by 70825** [jwtk/jjwt#799]
**Is your feature request related to a problem? Please describe.**

I find duplicate code and it seems like it can be refactored to eliminate the redundancy.

**Describe the solution you'd like**

All jobs are using the same value for the MVN_CMD environment variable in [ci.yml](https://github.com/jwtk/jjwt/blob/master/.github/workflows/ci.yml)

So I think it would be better to use a global environment variable

[AS-IS]

```yaml
jobs:
  oracle:
    env:
      MVN_CMD: ./mvnw --no-transfer-progress -B
  temurin:
    env:
      MVN_CMD: ./mvnw --no-transfer-progress -B
  ...
```

[TO-BE]

```yaml
env:
  MVN_CMD: ./mvnw --no-transfer-progress -B

...
```

**Describe alternatives you've considered**

x

**Additional context**

If you want this changed, can I try this issue?

I've always wanted to contribute directly to the JWT library that I've been using 😀
